homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%kawula_cms.locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'
